sudo: required

dist: focal

language: node_js

node_js:
 - "20"
services:
  - docker

before_install:
 - docker build -t piyush/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true piyush/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "eu-north-1"
 app: "Docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-eu-north-1-911167899687"
 bucket_path: "Docker"
 on:
   branch: main
 access_key_id: $AWS
 secret_access_key: $KEY


