sudo: required

dist: focal

language: node_js

node_js:
 - "20"
services:
  - docker

before_install:
 - docker build -t piyush/docker-react  -f Dockerfile.dev .

script:
 - docker run piyush/docker-react npm run test -- --coverage



